Define the parameters needed to install BOB, Smallrye ACP part of the run-skill. Check if BOBSHELL_API_KEY is available within run-skill. Remove non needed in/out paramaters within the action
Signed-off-by: Charles Moulliard <cmoulliard@ibm.com>

diff --git a/.github/workflows/run-skill.yml b/.github/workflows/run-skill.yml
--- a/.github/workflows/run-skill.yml
+++ b/.github/workflows/run-skill.yml
@@ -48,6 +48,10 @@ jobs:
 
       - name: Install ACP client and IBM Bob agent
         uses: ./base/.github/actions/acp-agent-action
+        with:
+          bobshell_base_url: "https://s3.us-south.cloud-object-storage.appdomain.cloud/bob-shell"
+          bobshell_version: 2.0.4
+          smallrye_acp_version: 0.2.0
 
       - name: Execute SKILL
         shell: bash
@@ -56,6 +60,11 @@ jobs:
           PROJECT_NAME: spring-rest-api
         run: |
           set -euo pipefail
+          
+          if [[ "${BOBSHELL_API_KEY}" != "true" ]]; then
+            echo "::error title=Bob configuration::BOBSHELL_API_KEY is missing"
+            exit 1
+          fi
 
           cd pr/tests
 
